import Head from 'next/head'
import { NextPage } from 'next/types'
import Main from '../../components/Main'
import CategoryPage from '../../components/views/Category/CategoryPage'
import { FilterContextProvider } from '../../contexts/FilterContext'
import { getProductsByQuery } from '../../firebase/firebaseRequests'
import { Product } from '../../types/interfaces'

interface CategoryProps {
  products: Product[]
}

const Category: NextPage<CategoryProps> = ({ products }) => {
  const [firstProduct] = products
  const { category } = firstProduct || ''

  return (
    <Main>
      <Head>
        <title>{category} | Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FilterContextProvider>
        <CategoryPage category={category} products={products} />
      </FilterContextProvider>
    </Main>
  )
}

export default Category

interface PathProps {
  params: { id: string; slug: string }
}

export const getServerSideProps = async (props: PathProps) => {
  const slug = props.params.slug
  const capitalize = slug.charAt(0).toUpperCase() + slug.slice(1)
  return {
    props: {
      products: await getProductsByQuery('where', 'category', capitalize)
    }
  }
}
