import type { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import Button from '../components/Button'
import Heading from '../components/Heading'
import Input from '../components/Input'
import ShelfItem from '../components/ShelfItem'
import { Product, useProductContext } from '../contexts/ProductContext'

const Admin: NextPage = () => {
  const {
    currentProducts,
    createProduct,
    getProducts,
    productDataForm,
    setProductDataForm,
    uploadProgress,
    inputFileRef
  } = useProductContext()

  const handleProduct = useCallback(
    (e: FormEvent<HTMLInputElement>) => {
      setProductDataForm({
        ...productDataForm,
        [e.currentTarget.name]: e.currentTarget.value
      })
    },
    [productDataForm]
  )

  // useEffect(() => {
  //   getProducts()
  // }, [])

  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Área do Usuário</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading text="Manipulação de Produtos" center />
      <div className="flex flex-col gap-6 max-w-xs">
        <Input
          text="Nome:"
          name="name"
          htmlFor="productName"
          required
          widthFull
          onChange={handleProduct}
        />
        <Input
          text="Preço:"
          name="price"
          type="number"
          htmlFor="productPrice"
          required
          widthFull
          onChange={handleProduct}
          value={productDataForm?.price}
        />
        <Input
          text="Melhor Preço:"
          name="bestPrice"
          type="number"
          htmlFor="productBestPrice"
          widthFull
          onChange={handleProduct}
          value={productDataForm?.bestPrice}
        />
        <Input
          text="Foto:"
          name="mainImg"
          type="file"
          htmlFor="productMainImg"
          widthFull
          onChange={handleProduct}
          value={productDataForm?.mainImg}
          reference={inputFileRef}
          accept="image/x-png,image/gif,image/jpeg"
        />
        <p>Uploaded {uploadProgress} %</p>

        <Button primary text="Cadastrar produto" onClick={createProduct} />
        <Button secondary text="Carregar produtos" onClick={getProducts} />
      </div>

      <section className="my-20">
        <ul className="flex flex-wrap gap-6 mt-6">
          {currentProducts?.map(({ id, name, price, bestPrice, mainImg }) => (
            <ShelfItem
              key={id}
              id={id}
              name={name}
              price={price}
              bestPrice={bestPrice}
              mainImg={mainImg}
            />
          ))}
        </ul>
      </section>
    </>
  )
}

export default Admin
