import Head from 'next/head'
import type { GetServerSideProps, NextPage } from 'next/types'
import { useEffect } from 'react'
import packageInfo from '../../package.json'
import Heading from '../components/Heading'
import ShelfSlider from '../components/ShelfSlider'
import { Product, useProductContext } from '../contexts/ProductContext'
import {
  getProductsByQuery,
  getProductsByServer
} from '../firebase/firebaseRequests'

interface IndexProps {
  allProducts: Product[]
  nikeShelfData: Product[]
  asicsShelfData: Product[]
  orangeShelfData: Product[]
}

const Index: NextPage<IndexProps> = ({
  allProducts,
  nikeShelfData,
  asicsShelfData,
  orangeShelfData
}) => {

  // useEffect(() => {
  //   getProductsByClient() // aqui os dados são gerados no cliente não por SSR
  // }, [])

  // useEffect(() => {
  //   setCurrentProducts(allProducts) //Setando no client dados vindos obtidos via SSR
  // }, [])

  return (
    <>
      <Head>
        <title>Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <section className="w-11/12 m-auto">
        <Heading text="Home" center />
        <p className="text-center">Versão {packageInfo.version}</p>

        <ShelfSlider data={allProducts} title="Todos os Produtos" />
        <ShelfSlider data={orangeShelfData} title="Rosas" />
        <ShelfSlider data={nikeShelfData} title="Só os Nikess" />
        <ShelfSlider data={asicsShelfData} title="Asics? Temos" />
      </section>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      allProducts: await getProductsByServer(),
      nikeShelfData: await getProductsByQuery('where', 'brand', 'Nike'),
      asicsShelfData: await getProductsByQuery('where', 'brand', 'Asics'),
      orangeShelfData: await getProductsByQuery('array', 'colors', 'Rosa')
    }
  }
}

export default Index
