import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import LoginInterface from '../components/Login/LoginInterface'
import { LoginContextProvider } from '../contexts/LoginContext'
import { useUserContext } from '../contexts/UserContext'
import { auth } from '../firebase/auth'

const Login: NextPage = () => {
  const { currentUser } = useUserContext()
  const router = useRouter()

  useEffect(() => {
    if (auth.currentUser?.uid) router.push('/')
  }, [currentUser])

  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginContextProvider>
        <LoginInterface />
      </LoginContextProvider>
    </>
  )
}
export default Login
