import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Heading from '../components/Heading'
import Input from '../components/Input'
import Button from '../components/Button'
import Main from '../components/Main'
import { MdLockOutline } from 'react-icons/md'

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <section>
          <Heading text="Login" center />
          <form
            className="m-auto flex flex-col gap-8"
            style={{ width: 'calc(min(90%, 20rem))' }}
          >
            <Input text="E-mail:" type="email" id="loginEmail" widthFull />
            <Input
              text="Senha:"
              type="password"
              id="loginPassword"
              icon={<MdLockOutline />}
              widthFull
            />
            <div className="flex justify-between flex-wrap">
              <Button primary text="Confirmar" />
              <Button secondary text="Entrar com o Google" google />
              <p className="flex-grow mt-4 text-xs">
                Esqueceu a senha? Clique{' '}
                <span className="text-primary font-semibold cursor-pointer">
                  aqui
                </span>
              </p>
            </div>
          </form>
        </section>
        <section className="mt-16">
          <Heading text="Criar Conta" center />
          <div className="flex justify-center w-full mt-6">
            <Button primary text="Criar agora" />
          </div>
        </section>
      </Main>
    </>
  )
}

export default Login
