import Head from 'next/head'
import { GetStaticProps, NextPage } from 'next/types'
import Main from '../components/Main'
import ProductsPage from '../components/views/Products/ProductsPage'
import { FilterContextProvider } from '../contexts/FilterContext'
import { getProductsByServer } from '../firebase/firebaseRequests'
import { Product } from '../types/interfaces'

interface ProductsProps {
  allProducts: Product[]
}

const Products: NextPage<ProductsProps> = ({ allProducts }) => {
  return (
    <Main>
      <Head>
        <title>Produtos | Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FilterContextProvider>
        <ProductsPage products={allProducts} />
      </FilterContextProvider>
    </Main>
  )
}

export default Products

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      allProducts: await getProductsByServer()
    },
    revalidate: 60 * 1 // 1 minute
  }
}
