import Head from 'next/head'
import { NextPage } from 'next/types'
import Main from '../components/Main'
import ProductsPage from '../components/views/Products/ProductsPage'
import { FilterContextProvider } from '../contexts/FilterContext'
import { getProductsByServer } from '../firebase/firebaseRequests'
import { Product } from '../types/interfaces'

interface ProductsProps {
  allProducts: Product[]
}

const Products: NextPage<ProductsProps> = ({ allProducts }) => {
  return (
    <Main>
      <Head>
        <title>Produtos | Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FilterContextProvider>
        <ProductsPage products={allProducts} />
      </FilterContextProvider>
    </Main>
  )
}

export default Products

interface PathProps {
  params: { id: string; slug: string }
}

export const getServerSideProps = async (props: PathProps) => {
  return {
    props: {
      allProducts: await getProductsByServer()
    }
  }
}
