import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import AnimationCelebration from '../components/Lottie/AnimationCelebration'
import { useGlobalContext } from '../contexts/GlobalContext'
import Button from '../components/Button'
import Heading from '../components/Heading'

const Sucess = () => {
  const { sucessOrder, isMobile } = useGlobalContext()
  const router = useRouter()

  useEffect(() => {
    if (!sucessOrder) router.push('/')
  }, [])

  if (!sucessOrder) return null

  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Sucesso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Heading text="Pedido confirmado" center small={isMobile} />
        <Link href="/">
          <a className="flex justify-center mt-16">
            <Button primary text="Ir para página inicial" />
          </a>
        </Link>
        <AnimationCelebration />
      </section>
    </>
  )
}

export default Sucess
