import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import Button from '../components/Button'
import Heading from '../components/Heading'
import { MdLogout, MdNoAccounts } from 'react-icons/md'
import { useAuthContext } from '../contexts/AuthContext'
import UserOption from '../components/UserOption'
import { useUserContext } from '../contexts/UserContext'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { AnimationOrder } from '../components/Lottie'
import DeliveryAdress from '../components/DeliveryAdress'
import PaymentMethod from '../components/PaymentMethod'
import Order from '../components/Order'

const User: NextPage = () => {
  const { logout } = useAuthContext()
  const { currentUser, getUser } = useUserContext()

  const [radio, setRadio] = useState('entrega')

  const router = useRouter()

  useEffect(() => {
    if (!currentUser?.uid) router.push('/login')
  }, [])

  useEffect(() => {
    getUser()
  }, [])

  if (!currentUser?.uid) return null

  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Área do Usuário</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading text="Área do Usuário" center />
      <section
        className="
          w-11/12 m-auto
          lg:w-full lg:flex
          pb-8
        "
      >
        <aside className="flex flex-col gap-6 lg:fixed">
          <UserOption
            radio={radio}
            setRadio={setRadio}
            text="Endereço de entrega"
            value="entrega"
          />
          <UserOption
            radio={radio}
            setRadio={setRadio}
            text="Meios de pagamento"
            value="pagamento"
          />
          <UserOption
            radio={radio}
            setRadio={setRadio}
            text="Compras realizadas"
            value="compras"
          />
          <div>
            <Button
              primary
              text="Fazer logout"
              icon={<MdLogout />}
              onClick={logout}
            />
          </div>
          <div>
            <Button
              secondary
              text="Deletar conta"
              icon={<MdNoAccounts />}
              onClick={logout}
            />
          </div>
        </aside>
        <article className="lg:absolute left-0 right-0 mt-6 m-auto w-full md:w-96">
          <div>
            {radio === 'entrega' && <DeliveryAdress orientation="vertical" />}
          </div>
          <div>
            {radio === 'pagamento' && <PaymentMethod orientation="vertical" />}
          </div>

          {radio === 'compras' && (
            <div className="flex flex-col gap-6">
              {currentUser?.orders?.length ? (
                currentUser?.orders
                  .slice()
                  .reverse()
                  .map(
                    ({
                      products,
                      totalValue,
                      adress,
                      paymentMethod,
                      timestamp
                    }) => (
                      <div className="border-b-2 pb-4">
                        <Order
                          products={products}
                          totalValue={totalValue}
                          adress={adress}
                          paymentMethod={paymentMethod}
                          timestamp={timestamp}
                        />
                      </div>
                    )
                  )
              ) : (
                <div className="flex justify-center items-center flex-col gap-4">
                  <AnimationOrder />
                  <p className="text-primary text-center">
                    Histórico de compras vazio.
                  </p>
                </div>
              )}
            </div>
          )}
        </article>
      </section>
    </>
  )
}

export default User
