import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../components/Button'
import Header from '../components/Header'
import Heading from '../components/Heading'
import Main from '../components/Main'
import { MdLogout } from 'react-icons/md'
import { useAuthContext } from '../contexts/AuthContext'

const Index: NextPage = () => {
  const { logout } = useAuthContext()

  return (
    <>
      <Head>
        <title>Fireshoes 🔥 | Área do Usuário</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Heading text="Área do Usuário" center />
        <p className="text-center">Essa é a Área do Usuário</p>
        <div className="flex justify-center m-8">
          <Button
            primary
            text="Fazer logout"
            icon={<MdLogout />}
            onClick={logout}
          />
        </div>
      </section>
    </>
  )
}

export default Index
