import Head from 'next/head'
import { NextPage } from 'next/types'
import Main from '../../components/Main'
import BrandPage from '../../components/views/Brand/BrandPage'
import { FilterContextProvider } from '../../contexts/FilterContext'
import { getProductsByQuery } from '../../firebase/firebaseRequests'
import { Product } from '../../types/interfaces'

interface BrandProps {
  products: Product[]
}

const Brand: NextPage<BrandProps> = ({ products }) => {
  const [firstProduct] = products
  const { brand } = firstProduct

  return (
    <Main>
      <Head>
        <title>{brand} | Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FilterContextProvider>
        <BrandPage brand={brand} products={products} />
      </FilterContextProvider>
    </Main>
  )
}

export default Brand

interface PathProps {
  params: { id: string; slug: string }
}

export const getServerSideProps = async (props: PathProps) => {
  const slug = props.params.slug
  const capitalize = slug.charAt(0).toUpperCase() + slug.slice(1)
  return {
    props: {
      products: await getProductsByQuery('where', 'brand', capitalize)
    }
  }
}
