import Head from 'next/head'
import { NextPage } from 'next/types'
import Main from '../../components/Main'
import BrandPage from '../../components/views/Brand/BrandPage'
import { FilterContextProvider } from '../../contexts/FilterContext'
import {
  getProductsByQuery,
  getProductsByServer
} from '../../firebase/firebaseRequests'
import { Product } from '../../types/interfaces'

interface BrandProps {
  products: Product[]
}

const Brand: NextPage<BrandProps> = ({ products }) => {
  const [firstProduct] = products
  const { brand } = firstProduct

  return (
    <Main>
      <Head>
        <title>{brand} | Fireshoes 🔥</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FilterContextProvider>
        <BrandPage brand={brand} products={products} />
      </FilterContextProvider>
    </Main>
  )
}

export default Brand

interface PathProps {
  params: { slug: string }
}

export const getStaticProps = async (props: PathProps) => {
  const slug = props.params.slug
  const capitalize = slug.charAt(0).toUpperCase() + slug.slice(1)
  return {
    props: {
      products: await getProductsByQuery('where', 'brand', capitalize)
    },
    revalidate: 60 * 1 // 1 minute
  }
}

export const getStaticPaths = async () => {
  const allProducts = await getProductsByServer()

  const uniques = new Set(allProducts?.map((product: Product) => product.brand))

  const paths = Array.from(uniques)?.map((brand) => ({
    params: { slug: brand }
  }))

  return {
    paths,
    fallback: 'blocking'
  }
}
